"""Initial migration

Revision ID: 9773f0b6dbab
Revises: 
Create Date: 2025-02-02 11:59:35.805611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9773f0b6dbab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educational_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregnancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('baby_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregnancy_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregnancy_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregnancy_symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregnancy_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('date_reported', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pregnancy_symptoms')
    op.drop_table('doctor_appointments')
    op.drop_table('baby_names')
    op.drop_table('symptoms')
    op.drop_table('pregnancies')
    op.drop_table('educational_resources')
    # ### end Alembic commands ###
